parameters:
    seiffert.helper.controller.router.class: Seiffert\ControllerHelperBundle\Helper\RouterHelper
    seiffert.helper.controller.template.class: Seiffert\ControllerHelperBundle\Helper\TemplateHelper
    seiffert.helper.controller.flash_message.class: Seiffert\ControllerHelperBundle\Helper\FlashMessageHelper
    seiffert.helper.controller.security.class: Seiffert\ControllerHelperBundle\Helper\SecurityHelper
    seiffert.helper.controller.form.class: Seiffert\ControllerHelperBundle\Helper\FormHelper
    seiffert.helper.controller.doctrine.class: Seiffert\ControllerHelperBundle\Helper\DoctrineHelper

services:
    seiffert.helper.controller.router:
        class: %seiffert.helper.controller.router.class%
        arguments: [ @?router ]
        tags:
            - { name: seiffert.helper, broker: seiffert.helper.controller }

    seiffert.helper.controller.template:
        class: %seiffert.helper.controller.template.class%
        arguments: [ @?templating ]
        tags:
            - { name: seiffert.helper, broker: seiffert.helper.controller }

    seiffert.helper.controller.flash_message:
        class: %seiffert.helper.controller.flash_message.class%
        arguments: [ @?session ]
        tags:
            - { name: seiffert.helper, broker: seiffert.helper.controller }

    seiffert.helper.controller.security:
        class: %seiffert.helper.controller.security.class%
        arguments: [ @?security.context ]
        tags:
            - { name: seiffert.helper, broker: seiffert.helper.controller }

    seiffert.helper.controller.form:
        class: %seiffert.helper.controller.form.class%
        arguments: [ @?form.factory ]
        tags:
            - { name: seiffert.helper, broker: seiffert.helper.controller }

    seiffert.helper.controller.doctrine:
        class: %seiffert.helper.controller.doctrine.class%
        arguments: [ @?doctrine.orm.entity_manager ]
        tags:
            - { name: seiffert.helper, broker: seiffert.helper.controller }
